/**
 * ngDesk_Operations
 * ngDesk_Operations
 *
 * OpenAPI spec version: 2.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.NgDeskOperations);
  }
}(this, function(expect, NgDeskOperations) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new NgDeskOperations.DefaultApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('DefaultApi', function() {
    describe('getTicket', function() {
      it('should call getTicket successfully', function(done) {
        //uncomment below and update the code to test getTicket
        //instance.getTicket(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getTickets', function() {
      it('should call getTickets successfully', function(done) {
        //uncomment below and update the code to test getTickets
        //instance.getTickets(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('postMessages', function() {
      it('should call postMessages successfully', function(done) {
        //uncomment below and update the code to test postMessages
        //instance.postMessages(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('postTickets', function() {
      it('should call postTickets successfully', function(done) {
        //uncomment below and update the code to test postTickets
        //instance.postTickets(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('putTickets', function() {
      it('should call putTickets successfully', function(done) {
        //uncomment below and update the code to test putTickets
        //instance.putTickets(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
